package com.xerago.rsa.dto.request;

import javax.xml.bind.annotation.XmlRootElement;

import io.swagger.annotations.ApiModelProperty;

@XmlRootElement(name="GPROPOSALREQUEST")
public class GProposalRequest {
	
	private AuthenticationDetails authenticationDetails;
	
	@ApiModelProperty(value = "This text is generated by application on response", required = true, example = "QVMN0020013")
	private String quoteId;
	
	@ApiModelProperty(value = "This text is generated by application on response", required = true, example = "1347")
	private String premium;
	
	@ApiModelProperty(value = "EmailId of propser", required = true, example = "blablabla@xerago.com")
	private String emailId;
	
	@ApiModelProperty(value = "Possible values are Yes/No", required = false, example = "Yes")
	private String isOTPVerified;
	
	public AuthenticationDetails getAuthenticationDetails() {
		return authenticationDetails;
	}
	public void setAuthenticationDetails(AuthenticationDetails authenticationDetails) {
		this.authenticationDetails = authenticationDetails;
	}
	public String getQuoteId() {
		return quoteId;
	}
	public void setQuoteId(String quoteId) {
		this.quoteId = quoteId;
	}	
	
	public String getPremium() {
		return premium;
	}
	public void setPremium(String premium) {
		this.premium = premium;
	}
	public String getEmailId() {
		return emailId;
	}
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	public String getIsOTPVerified() {
		return isOTPVerified;
	}
	public void setIsOTPVerified(String isOTPVerified) {
		this.isOTPVerified = isOTPVerified;
	}
	
}
