package com.xerago.rsa.model;
// Generated May 5, 2017 5:17:33 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * DTpSurveyReport generated by hbm2java
 */
@Entity
@Table(name="D_TP_SURVEY_REPORT")
public class DTpSurveyReport  implements java.io.Serializable {


     private String quoteId;
     private String status;
     private String registrationNumber;

    public DTpSurveyReport() {
    }

	
    public DTpSurveyReport(String quoteId) {
        this.quoteId = quoteId;
    }
    public DTpSurveyReport(String quoteId, String status, String registrationNumber) {
       this.quoteId = quoteId;
       this.status = status;
       this.registrationNumber = registrationNumber;
    }
    
    @Id
    @Column(name = "QUOTE_ID",length=30)
    public String getQuoteId() {
        return this.quoteId;
    }
    
    public void setQuoteId(String quoteId) {
        this.quoteId = quoteId;
    }
    @Column(name = "STATUS", length = 30)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    @Column(name = "REGISTRATION_NUMBER", length = 30)
	public String getRegistrationNumber() {
		return registrationNumber;
	}

	public void setRegistrationNumber(String registrationNumber) {
		this.registrationNumber = registrationNumber;
	}

}


