package com.xerago.rsa.model;
// Generated 11 Mar, 2017 3:01:04 PM by Hibernate Tools 4.3.1

import java.math.BigDecimal;

/**
 * Productcoveragemaster generated by hbm2java
 */

public class Productcoveragemaster implements java.io.Serializable {

	private long id;
	private String coveragename;
	private String productname;
	private String limitname;
	private String limittype;
	private BigDecimal defaultlimitvalue;
	private String deductiblename;
	private String deductibletype;
	private BigDecimal defaultdeductiblevalue;
	private String coveragedescription;
	private String limitdescription;
	private String deductibledescription;
	private Long ismandatory;
	private Long iscomposite;
	private Long parentcoverageid;
	private Long productid;
	private Long coveragedisplaytype;
	private Long isselected;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getCoveragename() {
		return coveragename;
	}

	public void setCoveragename(String coveragename) {
		this.coveragename = coveragename;
	}

	public String getProductname() {
		return productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getLimitname() {
		return limitname;
	}

	public void setLimitname(String limitname) {
		this.limitname = limitname;
	}

	public String getLimittype() {
		return limittype;
	}

	public void setLimittype(String limittype) {
		this.limittype = limittype;
	}

	public BigDecimal getDefaultlimitvalue() {
		return defaultlimitvalue;
	}

	public void setDefaultlimitvalue(BigDecimal defaultlimitvalue) {
		this.defaultlimitvalue = defaultlimitvalue;
	}

	public String getDeductiblename() {
		return deductiblename;
	}

	public void setDeductiblename(String deductiblename) {
		this.deductiblename = deductiblename;
	}

	public String getDeductibletype() {
		return deductibletype;
	}

	public void setDeductibletype(String deductibletype) {
		this.deductibletype = deductibletype;
	}

	public BigDecimal getDefaultdeductiblevalue() {
		return defaultdeductiblevalue;
	}

	public void setDefaultdeductiblevalue(BigDecimal defaultdeductiblevalue) {
		this.defaultdeductiblevalue = defaultdeductiblevalue;
	}

	public String getCoveragedescription() {
		return coveragedescription;
	}

	public void setCoveragedescription(String coveragedescription) {
		this.coveragedescription = coveragedescription;
	}

	public String getLimitdescription() {
		return limitdescription;
	}

	public void setLimitdescription(String limitdescription) {
		this.limitdescription = limitdescription;
	}

	public String getDeductibledescription() {
		return deductibledescription;
	}

	public void setDeductibledescription(String deductibledescription) {
		this.deductibledescription = deductibledescription;
	}

	public Long getIsmandatory() {
		return ismandatory;
	}

	public void setIsmandatory(Long ismandatory) {
		this.ismandatory = ismandatory;
	}

	public Long getIscomposite() {
		return iscomposite;
	}

	public void setIscomposite(Long iscomposite) {
		this.iscomposite = iscomposite;
	}

	public Long getParentcoverageid() {
		return parentcoverageid;
	}

	public void setParentcoverageid(Long parentcoverageid) {
		this.parentcoverageid = parentcoverageid;
	}

	public Long getProductid() {
		return productid;
	}

	public void setProductid(Long productid) {
		this.productid = productid;
	}

	public Long getCoveragedisplaytype() {
		return coveragedisplaytype;
	}

	public void setCoveragedisplaytype(Long coveragedisplaytype) {
		this.coveragedisplaytype = coveragedisplaytype;
	}

	public Long getIsselected() {
		return isselected;
	}

	public void setIsselected(Long isselected) {
		this.isselected = isselected;
	}

}
